name: Build Windows OT

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    env:
      VCPKG_ROOT: ${{ runner.temp }}/vcpkg
    steps:
      - uses: actions/checkout@v3

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git $Env:VCPKG_ROOT
          .\$Env:VCPKG_ROOT\bootstrap-vcpkg.bat
          .\$Env:VCPKG_ROOT\vcpkg.exe install --clean-after-build --triplet x64-windows

      - name: Configure and build
        run: cmake --preset windows-release && cmake --build --preset windows-release

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: theforgottenserver-win-x64
          path: build/windows-release/theforgottenserver.exe
